environment:
  nodejs_version: "8"

version: 1.0.{build}
init:
- ps: Install-Product node $env:nodejs_version
- ps: sleep 10
- ps: npm install npm@latest -g
- ps: node --version
- ps: npm --version

environment:
    GAUGE_PREFIX: C:\Program Files\Gauge\bin

build_script:
- ps: |
    Invoke-WebRequest -Uri "https://raw.githubusercontent.com/getgauge/infrastructure/master/nightly_scripts/install_latest_gauge_nightly.ps1" -OutFile install_latest_gauge_nightly.ps1
    .\install_latest_gauge_nightly.ps1
    $env:Path = "c:\Program Files\Gauge\bin;" + [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
    Write-Host "PATH : $($env:PATH)"
    gauge version
    gauge install
    gauge version
cache:
- packages
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/68b514dcb2c08a6a5809
  method: POST
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
test_script:
- ps: npm install
- ps: gauge run --env=js-wd --tags=\!knownIssue
artifacts:
- path: ./reports/html-report
  name: gauge-reports
- path: ./logs
  name: gauge-logs
- path: ./failure_reports/html-report
  name: gauge-reports-failure
on_finish:
- ps: >-
    # upload results to AppVeyor
    $wc = New-Object 'System.Net.WebClient'
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/gauge-lsp-tests-xml/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\reports\xml-report\result.xml))
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/gauge-lsp-tests-html/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\reports\html-report\index.html))
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/gauge-lsp-tests-logs/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\logs))
